name: gamepanel
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


#State Management & Utils
  get: ^4.6.1
  get_storage: ^2.0.3

#Fonts & Icons
  cupertino_icons: ^1.0.4
  google_fonts: ^2.3.1

#UI
  dotted_border: ^2.0.0+2
  hovering: ^1.0.4
  
#Game Stuff
  flame: ^1.1.1
  flame_tiled: ^1.4.0
  flame_forge2d: ^0.11.0
  flame_audio: ^1.0.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true



